import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import{HDate,HebrewCalendar,Event,flags}from'@hebcal/core';
import'./style.css';

const letters=['','א','ב','ג','ד','ה','ו','ז','ח','ט'];
function hebNum(n){
  if(n>=1000)return hebNum(Math.floor(n/1000))+'׳'+hebNum(n%1000);
  let s=''; const vals=[[400,'ת'],[300,'ש'],[200,'ר'],[100,'ק'],[90,'צ'],[80,'פ'],[70,'ע'],[60,'ס'],[50,'נ'],[40,'מ'],[30,'ל'],[20,'כ']];
  for(const[v,c]of vals)while(n>=v){s+=c;n-=v} if(n===15){s+='טו';n=0}if(n===16){s+='טז';n=0}if(n>=10){s+='י';n-=10}if(n)s+=letters[n];return s.length>1?s.slice(0,-1)+'״'+s.slice(-1):s+'׳';
}
const months=['','ניסן','אייר','סיוון','תמוז','אב','אלול','תשרי','חשוון','כסלו','טבת','שבט','אדר','אדר ב׳'];
const parshaHeb={'Bereshit':'בראשית','Noach':'נח','Lech-Lecha':'לך לך','Vayera':'וירא','Chayei-Sara':'חיי שרה','Toldot':'תולדות','Vayetzei':'ויצא','Vayishlach':'וישלח','Vayeshev':'וישב','Miketz':'מקץ','Vayigash':'ויגש','Vayechi':'ויחי','Shemot':'שמות','Vaera':'וארא','Bo':'בא','Beshalach':'בשלח','Yitro':'יתרו','Mishpatim':'משפטים','Terumah':'תרומה','Tetzaveh':'תצוה','Ki-Tisa':'כי תשא','Vayakhel':'ויקהל','Pekudei':'פקודי','Vayikra':'ויקרא','Tzav':'צו','Shmini':'שמיני','Tazria':'תזריע','Metzora':'מצורע','Achrei-Mot':'אחרי מות','Kedoshim':'קדושים','Emor':'אמור','Behar':'בהר','Bechukotai':'בחוקותי','Bamidbar':'במדבר','Nasso':'נשא','Beha’alotcha':'בהעלותך','Sh’lach':'שלח','Korach':'קרח','Chukat':'חקת','Balak':'בלק','Pinchas':'פינחס','Matot':'מטות','Masei':'מסעי','Devarim':'דברים','Vaetchanan':'ואתחנן','Eikev':'עקב','Re’eh':'ראה','Shoftim':'שופטים','Ki-Teitzei':'כי תצא','Ki-Tavo':'כי תבוא','Nitzavim':'נצבים','Vayeilech':'וילך','Ha’azinu':'האזינו'};
function fmtH(h){return `${hebNum(h.getDate())} ${months[h.getMonth()]} ${hebNum(h.getFullYear())}`}
function fmtG(d){return d.toLocaleDateString('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric',timeZone:'UTC'})}
function shabbatBefore(d){let x=new Date(d);let days=(x.getUTCDay()+1)%7;if(days===0)days=7;x.setUTCDate(x.getUTCDate()-days);return x}
function parshaFor(d){const ev=HebrewCalendar.calendar({start:d,end:d,sedrot:true,il:false}).find(e=>e.getFlags()&flags.PARSHA_HASHAVUA);if(!ev)return 'שבת מיוחדת / חג';return ev.getDesc().replace('Parashat ','').split('-').map(x=>parshaHeb[x]||x).join('־')}
function App(){const[date,setDate]=useState('');const[after,setAfter]=useState(false);const[gender,setGender]=useState('boy');const[result,setResult]=useState(null);function calc(e){e.preventDefault();if(!date)return;const g=new Date(date+'T12:00:00Z');if(after)g.setUTCDate(g.getUTCDate()+1);const h=new HDate(g);const years=gender==='boy'?13:12;const targetH=new HDate(h.getDate(),h.getMonth(),h.getFullYear()+years);const target=targetH.greg();const shab=shabbatBefore(target);setResult({h,targetH,target,shab,parsha:parshaFor(shab),years});}
return <main><section className="hero"><div className="mark">✡</div><p className="eyebrow">מזל טוב</p><h1>Jewish Birthday Calculator</h1><p>Discover a Hebrew birthday and Bar or Bat Mitzvah date.</p></section><section className="card"><form onSubmit={calc}><label>English date of birth<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><fieldset><legend>Was the birth before or after sunset?</legend><div className="choice"><button type="button" className={!after?'active':''} onClick={()=>setAfter(false)}>Before sunset</button><button type="button" className={after?'active':''} onClick={()=>setAfter(true)}>After sunset</button></div><small>In Judaism, a new calendar day begins at sunset.</small></fieldset><label>Calculate for<select value={gender} onChange={e=>setGender(e.target.value)}><option value="boy">Boy — Bar Mitzvah at 13</option><option value="girl">Girl — Bat Mitzvah at 12</option></select></label><button className="calculate">Calculate dates</button></form></section>{result&&<section className="results" dir="auto"><h2>Your results</h2><div className="grid"><article><span>Hebrew birthday</span><strong dir="rtl">{fmtH(result.h)}</strong><p>{fmtG(result.h.greg())}</p></article><article><span>{gender==='boy'?'Bar':'Bat'} Mitzvah date</span><strong dir="rtl">{fmtH(result.targetH)}</strong><p>{fmtG(result.target)}</p></article><article className="wide"><span>Shabbos before the {gender==='boy'?'Bar':'Bat'} Mitzvah</span><strong>{fmtG(result.shab)}</strong><p dir="rtl">פרשת {result.parsha}</p></article></div><p className="note">Dates are calendar calculations. Please confirm lifecycle-event details with your rabbi.</p></section>}<footer>Jewish dates begin at sunset.</footer></main>}
createRoot(document.getElementById('root')).render(<App/>);
